name: AI Doc Consistency & Lint

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.css'
      - '**/*.html'
      - '.github/copilot-instructions.md'
      - 'PROJECT-STATE.md'
      - 'README.md'
      - 'AGENT.md'
      - 'AGENTS.md'
  schedule:
    - cron: "0 3 * * 1" # Weekly, Mondays at 03:00 UTC

jobs:
  lint-docs:
    name: Lint AI Docs for Forbidden Patterns
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint for forbidden patterns
        run: |
          # Forbidden patterns for this repo's CSS-first, no-framework rules
          BAD_PATTERNS='class=|id=|data-|onclick=|onchange=|oninput=|<button'
          DOCS="README.md PROJECT-STATE.md AGENT.md AGENTS.md .github/copilot-instructions.md"
          set +e
          grep -nE "$BAD_PATTERNS" $DOCS
          STATUS=$?
          set -e
          if [ $STATUS -eq 0 ]; then
            echo "❌ Forbidden pattern found in docs. See lint output above." >&2
            exit 1
          else
            echo "✅ Docs lint clean."
          fi

  doc-drift:
    name: Detect Doc Drift (Architecture/AI Context)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for doc drift
        run: |
          # Patterns to enforce (expand as architecture grows)
          PATTERNS='input type="checkbox"|:has\(|@container|fieldset|aria-label|role="button"|Holy Grail|progressive enhancement'
          CODE_PATTERNS=$(grep -Ero "$PATTERNS" . --include=*.html --include=*.css --include=*.js | sed 's/.*://g' | sort | uniq)
          DOC_PATTERNS=$(grep -Ero "$PATTERNS" README.md PROJECT-STATE.md .github/copilot-instructions.md AGENT.md AGENTS.md | sed 's/.*://g' | sort | uniq)

          MISSING_DOCS=""
          for pat in $CODE_PATTERNS; do
            echo "$DOC_PATTERNS" | grep -qF "$pat" || MISSING_DOCS="$MISSING_DOCS $pat"
          done

          if [ -n "$MISSING_DOCS" ]; then
            echo "❌ Architectural patterns present in code but not in docs:"
            echo "$MISSING_DOCS"
            exit 1
          else
            echo "✅ No doc drift detected."
          fi

  notify-on-failure:
    name: Notify on Failure
    needs: [lint-docs, doc-drift]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Create Issue for Drift/Lint Failure
        uses: dacbd/create-issue-action@v1
        with:
          title: "AI Doc Consistency/Lint Failure"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            One or more AI documentation files have failed lint or drift detection.
            **Action Required:**  
            - Align `.github/copilot-instructions.md`, `PROJECT-STATE.md`, `README.md`, `AGENT.md`, and `AGENTS.md` with current repo architecture (HTML, CSS, JS patterns).
            - Remove forbidden patterns (class/id/data-*, inline handlers, <button>, etc).
            - Document all new or modified architecture patterns.
            - Review and re-run workflow before merging.
